In [2]:
import numpy as np

1.checking the shape ,size and dimentions of 1D,2D,3D arrays

In [3]:
a1 = np.array([1, 3, 5, 7])

In [4]:
a2 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])

In [5]:
a3= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

shape

In [6]:
print(a1.shape)

(4,)


In [7]:
print(a2.shape)

(2, 4)


In [8]:
print(a3.shape)

(2, 2, 2)


size

In [9]:
print(a1.size)

4


In [10]:
print(a2.size)

8


In [11]:
print(a3.size)

8


dimentions

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

2.write examples for following functions

i.arange

In [15]:
np.arange(1, 10, 3)

array([1, 4, 7])

ii.random randint

In [16]:
import random

In [21]:
r = np.random.randint(1, 123,6)

In [22]:
print (r)

[ 25  55  19   1 106 120]


In [ ]:
beg,end=1,1000
for i in range(5):
    print(random.randint(beg, end))

640
395
23
395
884


In [24]:
rr= np.random.rand(1, 123,6)
print(r)

[[[2.13679691e-01 1.56029965e-01 7.91453444e-01 8.89024203e-01
   5.93139555e-01 8.56593508e-01]
  [1.95111814e-01 4.26559941e-01 2.46445547e-01 7.34740056e-01
   1.08229871e-01 9.93108821e-01]
  [6.62231738e-01 2.73555628e-01 5.61986704e-01 4.03562789e-01
   2.94698132e-01 9.43701820e-01]
  [3.88717196e-01 7.21861239e-01 8.76832512e-01 2.56389361e-01
   1.32522124e-01 5.02905948e-01]
  [4.79487386e-01 3.30849034e-01 6.38344218e-01 8.41160382e-01
   8.61393920e-01 3.50945335e-01]
  [4.72974325e-01 4.55758109e-01 1.55367033e-01 5.88307860e-01
   6.41245998e-01 8.32458269e-01]
  [1.90119111e-02 7.94128518e-01 7.15477735e-01 7.85856729e-01
   5.65488631e-01 4.18387317e-01]
  [6.56014489e-01 7.71638611e-01 8.82291218e-01 6.43538269e-01
   8.52367053e-01 6.87970208e-01]
  [5.08185230e-01 5.72777980e-01 5.88245668e-01 9.08549843e-01
   1.13479742e-01 1.08117383e-01]
  [9.23385339e-01 3.34760189e-01 4.57504294e-01 3.54685735e-01
   5.73009360e-01 7.97190320e-01]
  [4.10549817e-01 4.85525534e-

linespace

In [ ]:
np.linspace(1, 5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

**ones**

In [27]:
arr1 = np.ones(3)
print(arr1)
arr2= np.ones((2, 3))
print(arr2)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


**zeros**

In [28]:
a3d = np.zeros((2, 3, 4))
print(a3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**diag**

In [30]:
diagarray = np.diag(a1, k=0)

print(a1)
print(diagarray)

[1 3 5 7]
[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


**sum**

In [32]:
a=np.array([0.4,0.5,0.9,6.1])
x=np.sum(a, dtype=np.int32)
x

6

**min**

In [33]:
array1 = np.array([10, 12, 14, 11, 5])
minValue= np.min(array1)
print(minValue)

5


**max**

In [34]:
maxValue= np.max(array1)
print(maxValue)

14


**mean**

In [35]:
a = np.array([[1, 2], [3, 4]])
b=np.mean(a)
b

2.5

**Make an array of student marks of a course(generate random marks).Assume fail criteria is less than 30. find number of students passed and filter failed marks**

In [43]:
std_marks = [random.randint(0, 100) for _ in range(50)]
passed_stds = [mark for mark in std_marks if mark >= 30]
failed_marks = [mark for mark in std_marks if mark < 30]

no_of_stds_passed= len(passed_stds)

print(f"Number of students passed: {no_of_stds_passed}")
print(f"Failed marks: {failed_marks}")

Number of students passed: 41
Failed marks: [28, 8, 26, 23, 26, 15, 16, 18, 6]


**Make a 2D array with random numbers between 1 and 50**

In [45]:
array2d = np.random.randint(50, size=(5, 5))
print(array2d)

[[39  0  3 44 44]
 [17 30 24 12 27]
 [45 36 16 16 33]
 [32 47 28 31 16]
 [45 27 31  4 28]]


**Make a numpy array for all odd numbers between -30 and 10**

In [49]:
odds = np.arange(-29, 11, 2)
print(odds)

[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
